-- MySQL Script generated by MySQL Workbench
-- Wed Feb 22 16:07:14 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema chefs_station
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `chefs_station` ;

-- -----------------------------------------------------
-- Schema chefs_station
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chefs_station` DEFAULT CHARACTER SET utf8 ;
USE `chefs_station` ;

-- -----------------------------------------------------
-- Table `chefs_station`.`receita`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chefs_station`.`receita` ;

CREATE TABLE IF NOT EXISTS `chefs_station`.`receita` (
  `receitaId` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(200) NULL,
  `tempopreparo` VARCHAR(45) NULL,
  `rendimento` VARCHAR(45) NULL,
  `dificuldade` VARCHAR(1) NULL,
  PRIMARY KEY (`receitaId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chefs_station`.`ingrediente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chefs_station`.`ingrediente` ;

CREATE TABLE IF NOT EXISTS `chefs_station`.`ingrediente` (
  `ingredienteId` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NOT NULL,
  `receitaId` INT NOT NULL,
  PRIMARY KEY (`ingredienteId`, `receitaId`),
  INDEX `fk_ingrediente_receita1_idx` (`receitaId` ASC) VISIBLE,
  CONSTRAINT `fk_ingrediente_receita1`
    FOREIGN KEY (`receitaId`)
    REFERENCES `chefs_station`.`receita` (`receitaId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chefs_station`.`preprapro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chefs_station`.`preprapro` ;

CREATE TABLE IF NOT EXISTS `chefs_station`.`preprapro` (
  `preparoId` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  `receitaId` INT NOT NULL,
  PRIMARY KEY (`preparoId`, `receitaId`),
  INDEX `fk_preprapro_receita_idx` (`receitaId` ASC) VISIBLE,
  CONSTRAINT `fk_preprapro_receita`
    FOREIGN KEY (`receitaId`)
    REFERENCES `chefs_station`.`receita` (`receitaId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chefs_station`.`etiqueta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chefs_station`.`etiqueta` ;

CREATE TABLE IF NOT EXISTS `chefs_station`.`etiqueta` (
  `etiquetaId` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`etiquetaId`),
  UNIQUE INDEX `uid_UNIQUE` (`etiquetaId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chefs_station`.`possui`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chefs_station`.`possui` ;

CREATE TABLE IF NOT EXISTS `chefs_station`.`possui` (
  `etiquetaId` INT NOT NULL,
  `receitaId` INT NOT NULL,
  PRIMARY KEY (`etiquetaId`, `receitaId`),
  INDEX `fk_etiqueta_has_receita_receita1_idx` (`receitaId` ASC) VISIBLE,
  INDEX `fk_etiqueta_has_receita_etiqueta1_idx` (`etiquetaId` ASC) VISIBLE,
  CONSTRAINT `fk_etiqueta_has_receita_etiqueta1`
    FOREIGN KEY (`etiquetaId`)
    REFERENCES `chefs_station`.`etiqueta` (`etiquetaId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_etiqueta_has_receita_receita1`
    FOREIGN KEY (`receitaId`)
    REFERENCES `chefs_station`.`receita` (`receitaId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
